In [1]:
import pandas as pd
import json
import pprint
pp = pprint.PrettyPrinter(indent=4)
import string
import random
import uuid

In [2]:
print('This example requires pandas greater than or equal to 1.3.0')
print("your running pandas: ", pd.__version__)
print("This also requires lxml package")
# conda install -c anaconda lxml

This example requires pandas greater than or equal to 1.3.0
your running pandas:  1.4.2
This also requires lxml package

## notes for creating a conda env for updated pandas (windows (not VID))

1 - open Anaconda powershell
2 - create a new env by runing (do not inclue '>')
    >conda create -n pd_env python=3 ipykernel pandas numpy lxml 
3 - enter you new env
    >conda activate pd_env
4 - make sure your in a dir you can wright too
    >cd $HOME 
5 - open up your perfered python interprator (we will assume jupyter notebooks)
    >jupyter-notebook

# we need to generate some data

In [3]:
# fun helps
def get_cat(N=3):
    '''returns a random ALPHA code from N possible codes'''
    letters = string.ascii_uppercase
    L = len(letters)
    if N > L**2:
        print('This definition need more logic to support sample space, N, '
              'grater than %s^2.\nSetting N=%s' % (L, L**2))
        N = L**2
    n = random.randint(1,N)
    return (string.ascii_uppercase[n-1] if (n < L) else
            '%s%s' % (string.ascii_uppercase[floor(n/L)-1],string.ascii_uppercase[(n%L)-1]))


def get_gender():
    '''returns a random gender'''
    return ['Male', 'Female'][random.randint(0,1)]

    
def get_id():
    '''returns a random universally unique identifier'''
    return str(uuid.uuid4()).replace('-','')

    
def mk_row(N=3):
    '''makes a random row of example data'''
    return [get_cat(N=N), get_gender(), get_id()]
    

def mk_example_df(I=10,N=3):
    '''makes a random dataframe of data for this example.
    input: I - number of rows you want
           N - number of categories in Cat variable column
           '''
    return pd.DataFrame([mk_row(N=N) for i in range(I)],
                        columns = ['Cat','Gender','id'])

# show how it works
mk_example_df(I=10)

  Cat  Gender                                id
0   A    Male  ff32cc26aa7644c8aae876e79558bea9
1   A  Female  49caab757ed34e6cabec65285e8415ca
2   A    Male  753389b819f24f999fb971c8ca0778ec
3   B  Female  3b7faa7716c146b3ad9bcb3a62ebe232
4   A    Male  dc00c36563b74f578a8dc6d5ca494c3c
5   B  Female  0b6501599c8d4e7f85946c276f57599b
6   A    Male  c218e8f5138f41bc950a1596e1ea649e
7   A  Female  9b67b7d691534ca5bc2b31e85fb4e4fa
8   A  Female  0d18b2e938f6482495da240f3643f742
9   B  Female  97644c77fceb4cd1b3a380bad5addc5b

In [4]:
# making example data
example_df = mk_example_df(I=100,N=10)
example_df

   Cat  Gender                                id
0    H    Male  068501e24d554cb89963b9f0cbdfa5cd
1    G    Male  31cd2e747c614c7db7e1b0104a8ccc2b
2    D  Female  c5c9cd206d824171bbccabe6f784c66d
3    B  Female  4c2397d908c64df3b5a5d62944002714
4    D  Female  d32159d3265e4fc4895407145dd1f08e
..  ..     ...                               ...
95   C    Male  3f7d69d044e4450f855f1d3ee16b7812
96   D    Male  1ab35c0dc1bd4d68b70168e5f1b3dc96
97   C  Female  710239b859214b5f9fc616a870c55095
98   D    Male  ae44dce5d06e481a9f5b587336a175d0
99   C  Female  b518c9b70eee43458ed647404dad1294

[100 rows x 3 columns]

# Now we will wright our example data

In [5]:
def dataframe_2_xml(df,file_path_str):
    '''wright df to file_path_srt as .xml'''
    if not '.xml' in file_path_str:
        raise Exception("Sorry, file_path_str must have .xml extension")
    elif type(df) != type(pd.DataFrame([])):
        raise TypeError("Sorry, df must be a pandas DataFrame")
    else:
        df.to_xml(file_path_str, index=False)

In [6]:
!DIR

 Volume in drive C is OSDisk
 Volume Serial Number is D021-0F9F

 Directory of C:\Users\scaly001\Documents\LocalOpenSourceProjects\NLP

07/13/2022  11:08 AM    <DIR>          .
07/13/2022  11:08 AM    <DIR>          ..
07/13/2022  09:48 AM    <DIR>          .ipynb_checkpoints
06/14/2022  11:48 AM            42,696 Conter_example.ipynb
06/14/2022  12:09 PM             6,027 Word.Movers.Distance.ipynb
07/13/2022  11:08 AM            15,237 xml_2_dict.ipynb
               3 File(s)         63,960 bytes
               3 Dir(s)  125,733,740,544 bytes free

In [7]:
dataframe_2_xml(example_df,"example_df.xml")

In [8]:
!DIR | findstr "example_df.xml"

07/13/2022  11:08 AM            10,758 example_df.xml

## Now we can start our example  

this is an example of reading in .xlm file and returning a dictionary

In [9]:
def read_xml_2_dict(file_path_str):
    '''reading in .xlm file and returning a dictionary'''
    if not '.xml' in file_path_str:
        raise Exception("Sorry, file_path_str must have .xml extension")
    else:
        return pd.read_xml("example_df.xml").to_dict()

def dict_wright(dict, file_path_str):
    '''wrights dictionary as json data'''
    if not '.json' in file_path_str:
        raise Exception("Sorry, file_path_str must have .json extension")
    else:
        with open(file_path_str, 'w') as f:
            json.dump(dict, f)

In [10]:
new_dict = read_xml_2_dict("example_df.xml")
dict_wright(new_dict, "new_dict.json")

In [11]:
!DIR | findstr "new_dict.json"

07/13/2022  11:08 AM             6,803 new_dict.json

In [12]:
pp.pprint(new_dict)

{   'Cat': {   0: 'H',
               1: 'G',
               2: 'D',
               3: 'B',
               4: 'D',
               5: 'D',
               6: 'C',
               7: 'A',
               8: 'H',
               9: 'F',
               10: 'D',
               11: 'B',
               12: 'D',
               13: 'G',
               14: 'F',
               15: 'G',
               16: 'A',
               17: 'C',
               18: 'A',
               19: 'G',
               20: 'H',
               21: 'E',
               22: 'C',
               23: 'J',
               24: 'B',
               25: 'J',
               26: 'I',
               27: 'F',
               28: 'J',
               29: 'I',
               30: 'B',
               31: 'A',
               32: 'E',
               33: 'B',
               34: 'G',
               35: 'B',
               36: 'E',
               37: 'A',
               38: 'F',
               39: 'C',
               40: 'F',
               41: 'G',
               42: 'F',
               43: 'C',
               44: 'B',
               45: 'G',
               46: 'F',
               47: 'A',
               48: 'D',
               49: 'G',
               50: 'A',
               51: 'H',
               52: 'G',
               53: 'E',
               54: 'C',
               55: 'I',
               56: 'E',
               57: 'C',
               58: 'D',
               59: 'H',
               60: 'E',
               61: 'C',
               62: 'G',
               63: 'E',
               64: 'H',
               65: 'F',
               66: 'J',
               67: 'H',
               68: 'A',
               69: 'E',
               70: 'J',
               71: 'C',
               72: 'F',
               73: 'D',
               74: 'F',
               75: 'C',
               76: 'B',
               77: 'C',
               78: 'A',
               79: 'G',
               80: 'I',
               81: 'H',
               82: 'B',
               83: 'F',
               84: 'A',
               85: 'F',
               86: 'C',
               87: 'B',
               88: 'H',
               89: 'I',
               90: 'C',
               91: 'B',
               92: 'A',
               93: 'G',
               94: 'G',
               95: 'C',
               96: 'D',
               97: 'C',
               98: 'D',
               99: 'C'},
    'Gender': {   0: 'Male',
                  1: 'Male',
                  2: 'Female',
                  3: 'Female',
                  4: 'Female',
                  5: 'Male',
                  6: 'Female',
                  7: 'Male',
                  8: 'Male',
                  9: 'Female',
                  10: 'Male',
                  11: 'Female',
                  12: 'Male',
                  13: 'Male',
                  14: 'Male',
                  15: 'Male',
                  16: 'Female',
                  17: 'Male',
                  18: 'Male',
                  19: 'Male',
                  20: 'Male',
                  21: 'Female',
                  22: 'Female',
                  23: 'Female',
                  24: 'Female',
                  25: 'Female',
                  26: 'Male',
                  27: 'Male',
                  28: 'Male',
                  29: 'Male',
                  30: 'Female',
                  31: 'Female',
                  32: 'Male',
                  33: 'Male',
                  34: 'Female',
                  35: 'Female',
                  36: 'Female',
                  37: 'Female',
                  38: 'Male',
                  39: 'Female',
                  40: 'Female',
                  41: 'Male',
                  42: 'Female',
                  43: 'Male',
                  44: 'Male',
                  45: 'Female',
                  46: 'Female',
                  47: 'Male',
                  48: 'Male',
                  49: 'Female',
                  50: 'Male',
                  51: 'Female',
                  52: 'Female',
                  53: 'Male',
                  54: 'Male',
                  55: 'Female',
                  56: 'Female',
                  57: 'Male',
                  58: 'Female',
                  59: 'Male',
                  60: 'Female',
                  61: 'Male',
                  62: 'Female',
                  63: 'Male',
                  64: 'Male',
                  65: 'Female',
                  66: 'Male',
                  67: 'Male',
                  68: 'Male',
                  69: 'Female',
                  70: 'Female',
                  71: 'Female',
                  72: 'Female',
                  73: 'Female',
                  74: 'Female',
                  75: 'Female',
                  76: 'Male',
                  77: 'Male',
                  78: 'Male',
                  79: 'Male',
                  80: 'Female',
                  81: 'Female',
                  82: 'Female',
                  83: 'Female',
                  84: 'Female',
                  85: 'Female',
                  86: 'Male',
                  87: 'Male',
                  88: 'Female',
                  89: 'Female',
                  90: 'Female',
                  91: 'Female',
                  92: 'Male',
                  93: 'Male',
                  94: 'Female',
                  95: 'Male',
                  96: 'Male',
                  97: 'Female',
                  98: 'Male',
                  99: 'Female'},
    'id': {   0: '068501e24d554cb89963b9f0cbdfa5cd',
              1: '31cd2e747c614c7db7e1b0104a8ccc2b',
              2: 'c5c9cd206d824171bbccabe6f784c66d',
              3: '4c2397d908c64df3b5a5d62944002714',
              4: 'd32159d3265e4fc4895407145dd1f08e',
              5: 'e1383174c7bd4013a65861e41a0bde28',
              6: '78310dc8ac3a4b1e8d120afdbac9c54c',
              7: '441aa6d1687d4085b4a05d3652c797ad',
              8: 'f3335089a0a64cb1a7c7612c593cd15b',
              9: 'e6462afb8fb245358a8a4ec7474d68e2',
              10: 'b428b45b19714c8eb15491b2463dfc40',
              11: '91f3aee53dd747ac8bcd39bbc2670a10',
              12: 'fc83828afdee4a8c8e2c08cc78a28980',
              13: 'c8fb3c60ab604b39a3298df0071fd95d',
              14: '038a0f986dc2440dbfb480b44d4446a2',
              15: '93626ba5fa5149c38e93eb728d59dbf6',
              16: 'ecb33742d4c94799a2edc74880c23b92',
              17: 'edd4310c4c974bd595b4d7cacc495827',
              18: '95855d6e4932466782892316227d6aaf',
              19: 'be8ca7da9ebb463599a82fa584553d98',
              20: '509b72e9225b42b2ac3ccb8d52dc7fc3',
              21: 'fcd151bc164a4d51a99f4accb86f7946',
              22: '97abc630ae6c4ca1bd7dc88ebe6de2c1',
              23: '85d3aadd8e1f4e1cb6ed3c1b92893ab2',
              24: '094c7c456f554fa5bbcee4ad553054e3',
              25: '51940d4fa3f54566a3c7833efdf75940',
              26: '47110125dd6946c2b6e4c61f15ad43fa',
              27: '190e437402684a7bb56b31be053941d9',
              28: 'd567edc00f31411b92619af170ff6012',
              29: '75d06c105ffa497e86b633fe5f39c189',
              30: '02859a1582384ccfa8507bf05a6fc55e',
              31: '6b07406a98014d218b4c2d2f7cde108d',
              32: '819f33fea2514becadf0aa3f68d52846',
              33: '9c22f766ded842629a58bbf34b5245e6',
              34: '4e02ba9eda9a4644bb60377700dab8c5',
              35: '9f33d90542464a208854112283fcccbf',
              36: 'a1363561a2314513ba032579a9a7d11b',
              37: '393b95ca2133413e90ad0eed6f199dc8',
              38: 'ef128bc7e39143a380e3f5ae99eb630c',
              39: '2a886a5dbab24fc8b03bc5ccdfe5927f',
              40: '2e05133439b74cda8b81993d276d790e',
              41: 'b82a7bd2b2d348aaafed7cd056187c7f',
              42: '21a091c8930647e5bd32a0bba414d7c0',
              43: 'a7ea97d05ca34bdd83ba1711180cef45',
              44: '97052e07c651424aa3015fcc54ae0f27',
              45: '61f8b5100b074766b4df9628261e15a8',
              46: '318eb35b9db140868fe05178f7841191',
              47: 'd1be7b0ef84f400cabc1c8968cf85337',
              48: 'bcea50adc4d54daaad52dda5f7deb1be',
              49: '65d0523c934f406f963bdd634bf5ebab',
              50: '1d72e9088ceb42a8bda57f5d6bc41ec8',
              51: '223ad424a07040c9945508ce1a32b62e',
              52: '00f6a2bf9b2f46f3bb9583fd1c8931ef',
              53: 'dc35ea60a7b84a678511c5a94c2b906d',
              54: '74fb1798610b45a087d15fa40101f9e2',
              55: '7e88320af71d4b4a9ddde6cfc1a4abfc',
              56: 'bb814ed9aa7b47229b1fd83b9fd75b55',
              57: '5877d7dea60f499f9a0a1ff9541b6903',
              58: 'd119eb8ab5384b50a57df697e748aea1',
              59: 'c2397ca9b1fe433daaa492421f03b2b1',
              60: '1c8bb161f44544a482fb4ff2da747102',
              61: 'a0e54aa2ae484117b7eed2a3cb9c3be9',
              62: 'f2a55d9902bc4dc7a06f902dc4b905e3',
              63: '963e4c848a50415ca11179b61715707a',
              64: '90621ffa7d2a41ff9b9e4eed1d057df6',
              65: '1133995f771f41808c9c80b745d0575e',
              66: '2840701d40624ab7ab9c64f5906c2187',
              67: '5bdc9cd10fd24904b23477979235b7ed',
              68: '894bdeae89fd49249355e5044aec6fa2',
              69: 'a26da4b131c7471d9698cc917b9dcd24',
              70: 'e60b4943d4ce4e8392a0c100a8fa12d0',
              71: 'b2cbe03ab4d74edeb15c70629c339220',
              72: '903b37aaf58b44749ef6205f024b5e67',
              73: '378338ababad4436930ec9af54f21e02',
              74: 'f2c3a6bb5bfb480eb9e18c1ad86eeabf',
              75: 'd535b27171ce4fdfac55fe9aac55d037',
              76: '03f58919ef734a36a1eb3058a0800d6b',
              77: '602fd789daf847409815d3e0663420f4',
              78: '95868aa65b984cab8a62bc8e5c1fd1b3',
              79: 'a207a60746e04219a5a99db3f52cbe91',
              80: 'a94e74a9ddce435891a74e8886415cdd',
              81: 'c0f5ae725ac4487a95908cb4acfab331',
              82: 'a2ae327a0c6a4141b4fa5135993c0124',
              83: 'db3978e8cbcf4fed87646cd877fe31d2',
              84: '19fad43793c4445aad1157fa84846893',
              85: '8f61be1eb09b4c839594e1841110e19c',
              86: 'de97524a5bbb4fe68e5cd0af0abe7b59',
              87: '9eddca1d022c4b53b7a1c6f3c53a379c',
              88: 'cf0a16477ee74346845e824023069a12',
              89: '786883c88f1940b4afd4672147c02ab7',
              90: 'f0f2458878714a6f9df4910af38b037e',
              91: '3aa60c3db5a0481e8088d440c667e68d',
              92: '357f0c758bfc474a96678c5478783ca3',
              93: 'dbd890a417a24c739c90618070be1b71',
              94: '03e1f2d4257c445e9f4e7f9b742533a4',
              95: '3f7d69d044e4450f855f1d3ee16b7812',
              96: '1ab35c0dc1bd4d68b70168e5f1b3dc96',
              97: '710239b859214b5f9fc616a870c55095',
              98: 'ae44dce5d06e481a9f5b587336a175d0',
              99: 'b518c9b70eee43458ed647404dad1294'}}

# End of File (EOF)